import { Budget } from "@/type";

const budgets: Budget[] = [
  {
    id: "1",
    createdAt: new Date("2026-09-01"),
    name: "Sakafo",
    amount: 250000,
    emoji: "🍚",
    transactions: [
      {
        id: "t1",
        amount: 45000,
        emoji: "🍚",
        description: "Courses au marché d'Anosibe",
        createdAt: new Date("2026-09-03"),
        budgetName: "Sakafo",
        budgetId: "1",
        category: "Alimentation",
      },
      {
        id: "t2",
        amount: 12000,
        emoji: "🥘",
        description: "Vary amin'anana",
        createdAt: new Date("2026-09-05"),
        budgetName: "Sakafo",
        budgetId: "1",
        category: "Alimentation",
      },
      {
        id: "t3",
        amount: 8000,
        emoji: "🥖",
        description: "Mofo sy café",
        createdAt: new Date("2026-09-07"),
        budgetName: "Sakafo",
        budgetId: "1",
        category: "Alimentation",
      },
      {
        id: "t4",
        amount: 25000,
        emoji: "🥩",
        description: "Viande et légumes",
        createdAt: new Date("2026-09-10"),
        budgetName: "Sakafo",
        budgetId: "1",
        category: "Alimentation",
      },
    ],
  },

  {
    id: "2",
    createdAt: new Date("2026-09-01"),
    name: "Transport",
    amount: 180000,
    emoji: "🚌",
    transactions: [
      {
        id: "t5",
        amount: 30000,
        emoji: "🚌",
        description: "Taxi-be",
        createdAt: new Date("2026-09-02"),
        budgetName: "Transport",
        budgetId: "2",
        category: "Transport",
      },
      {
        id: "t6",
        amount: 15000,
        emoji: "🚕",
        description: "Taxi",
        createdAt: new Date("2026-09-06"),
        budgetName: "Transport",
        budgetId: "2",
        category: "Transport",
      },
      {
        id: "t7",
        amount: 25000,
        emoji: "⛽",
        description: "Carburant",
        createdAt: new Date("2026-09-09"),
        budgetName: "Transport",
        budgetId: "2",
        category: "Transport",
      },
      {
        id: "t8",
        amount: 10000,
        emoji: "🏍️",
        description: "Déplacement en moto",
        createdAt: new Date("2026-09-12"),
        budgetName: "Transport",
        budgetId: "2",
        category: "Transport",
      },
    ],
  },

  {
    id: "3",
    createdAt: new Date("2026-09-01"),
    name: "Téléphone & Internet",
    amount: 120000,
    emoji: "📱",
    transactions: [
      {
        id: "t9",
        amount: 20000,
        emoji: "📱",
        description: "Crédit Telma",
        createdAt: new Date("2026-09-03"),
        budgetName: "Téléphone & Internet",
        budgetId: "3",
        category: "Abonnements",
      },
      {
        id: "t10",
        amount: 30000,
        emoji: "🌐",
        description: "Forfait Internet",
        createdAt: new Date("2026-09-05"),
        budgetName: "Téléphone & Internet",
        budgetId: "3",
        category: "Abonnements",
      },
      {
        id: "t11",
        amount: 15000,
        emoji: "📞",
        description: "Crédit Orange",
        createdAt: new Date("2026-09-11"),
        budgetName: "Téléphone & Internet",
        budgetId: "3",
        category: "Abonnements",
      },
    ],
  },

  {
    id: "4",
    createdAt: new Date("2026-09-01"),
    name: "Jirama & Maison",
    amount: 200000,
    emoji: "🏠",
    transactions: [
      {
        id: "t12",
        amount: 65000,
        emoji: "💡",
        description: "Facture Jirama",
        createdAt: new Date("2026-09-04"),
        budgetName: "Jirama & Maison",
        budgetId: "4",
        category: "Logement",
      },
      {
        id: "t13",
        amount: 30000,
        emoji: "💧",
        description: "Eau",
        createdAt: new Date("2026-09-06"),
        budgetName: "Jirama & Maison",
        budgetId: "4",
        category: "Logement",
      },
      {
        id: "t14",
        amount: 25000,
        emoji: "🧹",
        description: "Produits ménagers",
        createdAt: new Date("2026-09-09"),
        budgetName: "Jirama & Maison",
        budgetId: "4",
        category: "Logement",
      },
    ],
  },

  {
    id: "5",
    createdAt: new Date("2026-09-01"),
    name: "Études",
    amount: 150000,
    emoji: "🎓",
    transactions: [
      {
        id: "t15",
        amount: 35000,
        emoji: "📚",
        description: "Livres et supports de cours",
        createdAt: new Date("2026-09-02"),
        budgetName: "Études",
        budgetId: "5",
        category: "Études",
      },
      {
        id: "t16",
        amount: 15000,
        emoji: "🖨️",
        description: "Impressions",
        createdAt: new Date("2026-09-05"),
        budgetName: "Études",
        budgetId: "5",
        category: "Études",
      },
      {
        id: "t17",
        amount: 20000,
        emoji: "💻",
        description: "Cyber et travaux pratiques",
        createdAt: new Date("2026-09-08"),
        budgetName: "Études",
        budgetId: "5",
        category: "Études",
      },
    ],
  },

  {
    id: "6",
    createdAt: new Date("2026-09-01"),
    name: "Mobile Money",
    amount: 100000,
    emoji: "💸",
    transactions: [
      {
        id: "t18",
        amount: 30000,
        emoji: "📲",
        description: "Dépôt MVola",
        createdAt: new Date("2026-09-03"),
        budgetName: "Mobile Money",
        budgetId: "6",
        category: "Autres",
      },
      {
        id: "t19",
        amount: 20000,
        emoji: "📲",
        description: "Transfert Orange Money",
        createdAt: new Date("2026-09-07"),
        budgetName: "Mobile Money",
        budgetId: "6",
        category: "Autres",
      },
    ],
  },

  {
    id: "7",
    createdAt: new Date("2026-09-01"),
    name: "Loisirs",
    amount: 100000,
    emoji: "🎉",
    transactions: [
      {
        id: "t20",
        amount: 20000,
        emoji: "⚽",
        description: "Match de foot avec les amis",
        createdAt: new Date("2026-09-06"),
        budgetName: "Loisirs",
        budgetId: "7",
        category: "Loisirs",
      },
      {
        id: "t21",
        amount: 15000,
        emoji: "🍻",
        description: "Sortie entre amis",
        createdAt: new Date("2026-09-09"),
        budgetName: "Loisirs",
        budgetId: "7",
        category: "Loisirs",
      },
      {
        id: "t22",
        amount: 10000,
        emoji: "🎬",
        description: "Cinéma",
        createdAt: new Date("2026-09-13"),
        budgetName: "Loisirs",
        budgetId: "7",
        category: "Loisirs",
      },
    ],
  },

  {
    id: "8",
    createdAt: new Date("2026-09-01"),
    name: "Épargne",
    amount: 300000,
    emoji: "💰",
    transactions: [
      {
        id: "t23",
        amount: 100000,
        emoji: "🏦",
        description: "Épargne mensuelle",
        createdAt: new Date("2026-09-01"),
        budgetName: "Épargne",
        budgetId: "8",
        category: "Autres",
      },
      {
        id: "t24",
        amount: 50000,
        emoji: "🐷",
        description: "Tahiry / épargne personnelle",
        createdAt: new Date("2026-09-10"),
        budgetName: "Épargne",
        budgetId: "8",
        category: "Autres",
      },
    ],
  },
];

export default budgets;